# Generated by Django 3.0.5 on 2022-07-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('text', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
