# Generated by Django 3.0.5 on 2022-07-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'managed': False},
        ),
    ]
