# Generated by Django 3.0.5 on 2022-07-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_auto_20220723_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
