# Generated by Django 3.0.5 on 2022-08-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0005_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('last_sale', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
