# Generated by Django 3.0.5 on 2022-08-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0006_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': False},
        ),
    ]
