# Generated by Django 3.0.5 on 2022-08-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0007_auto_20220804_1905'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='Inventory',
        ),
    ]
