# Generated by Django 3.0.5 on 2022-09-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0008_auto_20220804_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'Managers',
                'managed': False,
            },
        ),
    ]
