# Generated by Django 3.0.5 on 2022-09-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0009_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Managers',
        ),
    ]
