# Generated by Django 3.0.5 on 2022-09-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0011_managers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='managers',
            table='managers',
        ),
    ]
