# Generated by Django 3.0.5 on 2022-09-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0012_auto_20220916_1502'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
