# Generated by Django 3.0.5 on 2022-09-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0013_auto_20220916_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(blank=True, max_length=25, null=True)),
                ('location', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
    ]
